pricing: 
  # Instance Based Pricing: SageMaker, EKS, Bedrock Provisioned Throughput, Bring your own endpoints that are priced hourly
  # SageMaker Hourly Instance Pricing
  ml.m5.xlarge: 0.23
  ml.g5.xlarge: 1.006
  ml.g5.2xlarge: 1.212
  ml.g5.12xlarge: 7.09
  ml.g5.24xlarge: 10.18
  ml.g5.48xlarge: 20.36
  ml.inf2.24xlarge: 7.79
  ml.inf2.48xlarge: 15.58
  ml.p4d.24xlarge: 37.688
  ml.p3.2xlarge: 3.825

  # Token Based Pricing: Bedrock (On Demand Throughput)
  # Claude
  Claudev3-Haiku-ODT:
  - input-per-1k-tokens: 0.00025
  - output-per-1k-tokens: 0.00125
  Claudev3-Sonnet-ODT:
  - input-per-1k-tokens: 0.00300
  - output-per-1k-tokens: 0.01500
  ClaudeV2-ODT: 
  - input-per-1k-tokens: 0.000800 
  - output-per-1k-tokens: 0.002400
  ClaudeV2:1-ODT: 
  - input-per-1k-tokens: 0.000800 
  - output-per-1k-tokens: 0.002400
  ClaudeInstant-ODT: 
  - input-per-1k-tokens: 0.00080 
  - output-per-1k-tokens: 0.00240 
  # Titan
  titan-emb-text-ODT: 
  - input-per-1k-tokens: 0.0001
  - output-per-1k-tokens: 0 # n/a
  titan-text-lite-ODT: 
  - input-per-1k-tokens: 0.0003
  - output-per-1k-tokens: 0.0004
  titan-text-express-ODT: 
  - input-per-1k-tokens: 0.0008
  - output-per-1k-tokens: 0.0016
  # Mistral & Mixtral
  Mistral-ODT:
  - input-per-1k-tokens: 0.00015
  - output-per-1k-tokens: 0.0002
  Mixtral-ODT: 
  - input-per-1k-tokens: 0.00045
  - output-per-1k-tokens: 0.0007
  ## Llama
  Llama13b-ODT:
  - input-per-1k-tokens: 0.00075
  - output-per-1k-tokens: 0.00100
  Llama70b-ODT: 
  - input-per-1k-tokens: 0.00195
  - output-per-1k-tokens: 0.00195
  #  ai21
  AI21mid-ODT:
  - input-per-1k-tokens: 0.0125
  - output-per-1k-tokens: 0.0125
  AI21ultra-ODT: 
  - input-per-1k-tokens: 0.0188
  - output-per-1k-tokens: 0.0188
  # Cohere
  CohereCommand-ODT: 
  - input-per-1k-tokens: 0.0015
  - output-per-1k-tokens: 0.0020
  CohereCommLight-ODT: 
  - input-per-1k-tokens: 0.0003
  - output-per-1k-tokens: 0.0006